"""Deterministic buyer-policy evaluation and SolutionPlan ordering."""

from .bounds import (
    BoundedPlan,
    CostBounds,
    CoverageBounds,
    CoverageCriterion,
    EvidenceAgeBounds,
    ExactRatio,
    OrderingBounds,
    PreferenceCriterionBound,
    PreferenceScoreBounds,
    RankStabilityResult,
    RiskBounds,
    aggregate_coverage_bounds,
    aggregate_evidence_age_bounds,
    aggregate_preference_bounds,
    aggregate_risk_bounds,
    assess_rank_stability,
    authoritative_ordering_key,
    evidence_age_bounds,
)
from .counterfactual import build_counterfactual
from .demo import DemoDecision, evaluate_demo
from .evaluation import evaluate_candidate, evaluate_candidate_set
from .graph_v1 import (
    build_solution_plans,
    evaluate_decision_graph,
    evaluate_decision_graph_once,
    evaluate_gates,
    evaluation_canonical_payload,
    search_private_fact_counterfactuals,
)
from .graph_v1_fixtures import (
    DecisionSourceBundle,
    compile_decision_graph_input,
    load_demo_decision_graph_input,
    load_demo_decision_source,
)
from .graph_v1_models import (
    ActorConflictResolution,
    CounterfactualOutcome,
    CounterfactualRecord,
    DecisionGraphDecision,
    DecisionGraphEvaluation,
    DecisionGraphInput,
    EvaluatedPlan,
    EvidenceAssessment,
    EvidenceState,
    FactProvenance,
    GateResult,
    IdentityMerge,
    IdentityRecord,
    PlanLifecycle,
    RecallExclusion,
    RecallPolicy,
)
from .graph_v1_recall import assess_evidence, recall_and_deduplicate
from .models import (
    BuyerConstraint,
    CandidateDefinition,
    CandidateResult,
    Counterfactual,
    PreferenceResult,
    SellerAntiFitRule,
    SolutionPlan,
)
from .ranking import rank_solution_plans, ranking_key, select_winner

__all__ = [
    "ActorConflictResolution",
    "BoundedPlan",
    "BuyerConstraint",
    "CandidateDefinition",
    "CandidateResult",
    "CostBounds",
    "Counterfactual",
    "CounterfactualOutcome",
    "CounterfactualRecord",
    "CoverageBounds",
    "CoverageCriterion",
    "DecisionGraphDecision",
    "DecisionGraphEvaluation",
    "DecisionGraphInput",
    "DecisionSourceBundle",
    "DemoDecision",
    "EvaluatedPlan",
    "EvidenceAgeBounds",
    "EvidenceAssessment",
    "EvidenceState",
    "ExactRatio",
    "FactProvenance",
    "GateResult",
    "IdentityMerge",
    "IdentityRecord",
    "OrderingBounds",
    "PlanLifecycle",
    "PreferenceCriterionBound",
    "PreferenceResult",
    "PreferenceScoreBounds",
    "RankStabilityResult",
    "RecallExclusion",
    "RecallPolicy",
    "RiskBounds",
    "SellerAntiFitRule",
    "SolutionPlan",
    "aggregate_coverage_bounds",
    "aggregate_evidence_age_bounds",
    "aggregate_preference_bounds",
    "aggregate_risk_bounds",
    "assess_evidence",
    "assess_rank_stability",
    "authoritative_ordering_key",
    "build_counterfactual",
    "build_solution_plans",
    "compile_decision_graph_input",
    "evaluate_candidate",
    "evaluate_candidate_set",
    "evaluate_decision_graph",
    "evaluate_decision_graph_once",
    "evaluate_demo",
    "evaluate_gates",
    "evaluation_canonical_payload",
    "evidence_age_bounds",
    "load_demo_decision_graph_input",
    "load_demo_decision_source",
    "rank_solution_plans",
    "ranking_key",
    "recall_and_deduplicate",
    "search_private_fact_counterfactuals",
    "select_winner",
]
