"""Pure SIRA + SEIL domain contracts.

This package intentionally depends only on the Python standard library.  HTTP,
persistence, provider, workflow, and agent-runtime concerns belong behind
adapters in their respective packages.
"""

from .enums import (
    ActorRole,
    ApprovalStatus,
    CandidateAction,
    CandidateStatus,
    DecisionOutcome,
    DecisionStage,
    DecisionVersionState,
    EngagementStatus,
    ExecutionStepStatus,
    ExecutionStepType,
    FulfillmentStatus,
    OperationStatus,
    OptionFeedbackAction,
    OutcomeState,
    PackAuthority,
    PaymentStatus,
    PlanSelectionState,
    ProductInstanceState,
    PurchaseState,
    RankStability,
    RequestVisibility,
    ResultArtifactType,
    ReversalStatus,
    RuleOperator,
    SellerEvidenceState,
    SellerExportFormat,
    SellerReviewDecision,
    SolutionAction,
    SolutionActionType,
    SolutionOptionStatus,
    SolutionPlanLifecycle,
    StackPatchStatus,
    StackRisk,
    StageStatus,
    TruthValue,
    UIActionCapability,
)
from .errors import DomainValidationError, InvalidTransitionError
from .hashing import canonical_json, content_hash
from .models import (
    ApprovalBinding,
    BuyerFact,
    EvidenceRef,
    ExpectedFulfillment,
    MerchantIdentity,
    PurchaseIntent,
    SourceRef,
    Verification,
)
from .money import Money
from .publication import (
    DEFAULT_PACK_PUBLICATION_ALLOWLIST,
    DEFAULT_REQUIREMENT_BRIEF_ALLOWLIST,
    assert_public_payload,
    publish_seil_pack,
    sanitize_requirement_brief,
)
from .rules import RuleCondition, RuleEvaluation, RuleExpression, resolve_field
from .state_machines import (
    ApprovalTransitionService,
    FulfillmentTransitionService,
    PaymentTransitionService,
    ReversalTransitionService,
    derive_purchase_state,
)

__all__ = [
    "DEFAULT_PACK_PUBLICATION_ALLOWLIST",
    "DEFAULT_REQUIREMENT_BRIEF_ALLOWLIST",
    "ActorRole",
    "ApprovalBinding",
    "ApprovalStatus",
    "ApprovalTransitionService",
    "BuyerFact",
    "CandidateAction",
    "CandidateStatus",
    "DecisionOutcome",
    "DecisionStage",
    "DecisionVersionState",
    "DomainValidationError",
    "EngagementStatus",
    "EvidenceRef",
    "ExecutionStepStatus",
    "ExecutionStepType",
    "ExpectedFulfillment",
    "FulfillmentStatus",
    "FulfillmentTransitionService",
    "InvalidTransitionError",
    "MerchantIdentity",
    "Money",
    "OperationStatus",
    "OptionFeedbackAction",
    "OutcomeState",
    "PackAuthority",
    "PaymentStatus",
    "PaymentTransitionService",
    "PlanSelectionState",
    "ProductInstanceState",
    "PurchaseIntent",
    "PurchaseState",
    "RankStability",
    "RequestVisibility",
    "ResultArtifactType",
    "ReversalStatus",
    "ReversalTransitionService",
    "RuleCondition",
    "RuleEvaluation",
    "RuleExpression",
    "RuleOperator",
    "SellerEvidenceState",
    "SellerExportFormat",
    "SellerReviewDecision",
    "SolutionAction",
    "SolutionActionType",
    "SolutionOptionStatus",
    "SolutionPlanLifecycle",
    "SourceRef",
    "StackPatchStatus",
    "StackRisk",
    "StageStatus",
    "TruthValue",
    "UIActionCapability",
    "Verification",
    "assert_public_payload",
    "canonical_json",
    "content_hash",
    "derive_purchase_state",
    "publish_seil_pack",
    "resolve_field",
    "sanitize_requirement_brief",
]
