"""Shared, stable enum values for the first vertical workflow."""

from enum import StrEnum

StringEnum = StrEnum


class CandidateStatus(StringEnum):
    ELIGIBLE = "ELIGIBLE"
    ELIGIBLE_WITH_EXCEPTION = "ELIGIBLE_WITH_EXCEPTION"
    CONDITIONAL = "CONDITIONAL"
    SIRA_INELIGIBLE = "SIRA_INELIGIBLE"
    SEIL_PASS = "SEIL_PASS"  # noqa: S105 - product status, not a password
    UNAVAILABLE = "UNAVAILABLE"
    STALE_EVIDENCE = "STALE_EVIDENCE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    AUTHORITY_REQUIRED = "AUTHORITY_REQUIRED"
    ADVISORY_ONLY = "ADVISORY_ONLY"


class SolutionOptionStatus(StringEnum):
    SUPPORTED = "SUPPORTED"
    SUPPORTED_WITH_EXCEPTION = "SUPPORTED_WITH_EXCEPTION"
    NEEDS_CONDITION = "NEEDS_CONDITION"
    BLOCKED_BY_COMPANY_REQUIREMENT = "BLOCKED_BY_COMPANY_REQUIREMENT"
    VENDOR_NOT_SUPPORTED = "VENDOR_NOT_SUPPORTED"
    UNAVAILABLE = "UNAVAILABLE"
    NEEDS_EVIDENCE = "NEEDS_EVIDENCE"
    EVIDENCE_CONFLICT = "EVIDENCE_CONFLICT"
    AUTHORITY_REQUIRED = "AUTHORITY_REQUIRED"
    RESEARCH_ONLY = "RESEARCH_ONLY"


class DecisionOutcome(StringEnum):
    SELECTED_SOLUTION_PLAN = "SELECTED_SOLUTION_PLAN"
    NO_ELIGIBLE_SUPPORTED_ACTION = "NO_ELIGIBLE_SUPPORTED_ACTION"


class RankStability(StringEnum):
    STABLE = "STABLE"
    UNSTABLE = "UNSTABLE"
    UNDETERMINED = "UNDETERMINED"


class PackAuthority(StringEnum):
    SELLER_SEALED = "SELLER_SEALED"
    PLATFORM_COMPILED = "PLATFORM_COMPILED"
    EXTERNAL_UNSEALED = "EXTERNAL_UNSEALED"


class ApprovalStatus(StringEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    NOT_REQUESTED = "NOT_REQUESTED"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


class PaymentStatus(StringEnum):
    """Persisted first-build payment states.

    A one-time Prava credential deliberately has no persisted state: it exists
    only in the isolated checkout operation between CARDHOLDER_PENDING and
    CHECKOUT_PENDING.
    """

    NOT_REQUIRED = "NOT_REQUIRED"
    NOT_STARTED = "NOT_STARTED"
    SESSION_CREATED = "SESSION_CREATED"
    CARDHOLDER_PENDING = "CARDHOLDER_PENDING"
    CHECKOUT_PENDING = "CHECKOUT_PENDING"
    MERCHANT_APPROVED = "MERCHANT_APPROVED"
    REPORTING = "REPORTING"
    PRAVA_COMPLETED = "PRAVA_COMPLETED"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"
    UNCERTAIN = "UNCERTAIN"
    FAILED = "FAILED"


class FulfillmentStatus(StringEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    NOT_STARTED = "NOT_STARTED"
    PENDING = "PENDING"
    PARTIAL = "PARTIAL"
    VERIFIED = "VERIFIED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_FINAL = "FAILED_FINAL"
    REVOKED = "REVOKED"


class PurchaseState(StringEnum):
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED_NOT_STARTED = "APPROVED_NOT_STARTED"
    PAYMENT_IN_PROGRESS = "PAYMENT_IN_PROGRESS"
    PAYMENT_NOT_COMPLETED = "PAYMENT_NOT_COMPLETED"
    PAYMENT_UNCERTAIN = "PAYMENT_UNCERTAIN"
    PAID_UNFULFILLED = "PAID_UNFULFILLED"
    PURCHASE_FULFILLED = "PURCHASE_FULFILLED"
    REFUND_PENDING = "REFUND_PENDING"
    REFUNDED = "REFUNDED"


class ReversalStatus(StringEnum):
    REQUESTED = "REQUESTED"
    PROVIDER_PENDING = "PROVIDER_PENDING"
    PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED"
    REFUNDED = "REFUNDED"
    REJECTED = "REJECTED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    COMPENSATION_REQUIRED = "COMPENSATION_REQUIRED"
    COMPENSATED = "COMPENSATED"
    CANCELLED = "CANCELLED"


class OutcomeState(StringEnum):
    NOT_MEASURED = "NOT_MEASURED"
    MEASURING = "MEASURING"
    ACHIEVED = "ACHIEVED"
    NOT_ACHIEVED = "NOT_ACHIEVED"
    INCONCLUSIVE = "INCONCLUSIVE"


class RequestVisibility(StringEnum):
    PRIVATE = "PRIVATE"
    SELECTIVE = "SELECTIVE"
    OPEN_RFP = "OPEN_RFP"


class CandidateAction(StringEnum):
    SHORTLIST = "SHORTLIST"
    PASS = "PASS"  # noqa: S105 - buyer feedback action, not a password
    REQUEST_OFFER = "REQUEST_OFFER"
    SAVE_FOR_LATER = "SAVE_FOR_LATER"
    NOT_ENOUGH_EVIDENCE = "NOT_ENOUGH_EVIDENCE"


class OptionFeedbackAction(StringEnum):
    KEEP_FOR_COMPARISON = "KEEP_FOR_COMPARISON"
    ELIMINATE = "ELIMINATE"
    ASK_VENDOR = "ASK_VENDOR"
    SAVE = "SAVE"
    NEED_EVIDENCE = "NEED_EVIDENCE"


class EngagementStatus(StringEnum):
    NOT_STARTED = "NOT_STARTED"
    SELLER_REVIEWING = "SELLER_REVIEWING"
    SELLER_PASSED = "SELLER_PASSED"
    OFFER_AVAILABLE = "OFFER_AVAILABLE"
    BUYER_CONSENT_PENDING = "BUYER_CONSENT_PENDING"
    SELLER_CONSENT_PENDING = "SELLER_CONSENT_PENDING"
    INTRODUCTION_READY = "INTRODUCTION_READY"
    DECLINED = "DECLINED"
    EXPIRED = "EXPIRED"


class SolutionAction(StringEnum):
    REUSE_EXISTING = "REUSE_EXISTING"
    CONFIGURE_EXISTING = "CONFIGURE_EXISTING"
    NO_ACTION = "NO_ACTION"
    BUY = "BUY"
    RENEW = "RENEW"
    RESIZE = "RESIZE"
    REPLACE = "REPLACE"
    CONSOLIDATE = "CONSOLIDATE"
    CANCEL = "CANCEL"


class SolutionActionType(StringEnum):
    REUSE_EXISTING = "REUSE_EXISTING"
    CONFIGURE_EXISTING = "CONFIGURE_EXISTING"
    NO_ACTION = "NO_ACTION"
    BUY = "BUY"
    RENEW = "RENEW"
    RESIZE = "RESIZE"
    REPLACE = "REPLACE"
    CONSOLIDATE = "CONSOLIDATE"
    CANCEL = "CANCEL"


class SolutionPlanLifecycle(StringEnum):
    CANDIDATE = "CANDIDATE"
    RESOLUTION_PENDING = "RESOLUTION_PENDING"
    EXECUTABLE = "EXECUTABLE"
    BLOCKED = "BLOCKED"


class PlanSelectionState(StringEnum):
    SELECTED = "SELECTED"
    SUPERSEDED = "SUPERSEDED"
    CANCELLED = "CANCELLED"


class DecisionStage(StringEnum):
    NEED = "NEED"
    COMPANY_FIT = "COMPANY_FIT"
    OPTIONS = "OPTIONS"
    ACTION = "ACTION"
    RESULT = "RESULT"


class StageStatus(StringEnum):
    NOT_STARTED = "NOT_STARTED"
    READY = "READY"
    CURRENT = "CURRENT"
    WAITING = "WAITING"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    SUPERSEDED = "SUPERSEDED"


class DecisionVersionState(StringEnum):
    CURRENT = "CURRENT"
    SUPERSEDED = "SUPERSEDED"


class OperationStatus(StringEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_FOR_HUMAN = "WAITING_FOR_HUMAN"
    RETRYABLE_ERROR = "RETRYABLE_ERROR"
    UNCERTAIN = "UNCERTAIN"
    COMPLETED = "COMPLETED"
    FAILED_FINAL = "FAILED_FINAL"


class ExecutionStepType(StringEnum):
    REVIEW = "REVIEW"
    REQUIRED_AUTHORITY = "REQUIRED_AUTHORITY"
    EXECUTE_OR_ASSIGN = "EXECUTE_OR_ASSIGN"
    VERIFY = "VERIFY"


class ExecutionStepStatus(StringEnum):
    NOT_REACHED = "NOT_REACHED"
    AVAILABLE = "AVAILABLE"
    CURRENT = "CURRENT"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    SKIPPED = "SKIPPED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_FINAL = "FAILED_FINAL"


class ActorRole(StringEnum):
    REQUESTER = "REQUESTER"
    DECISION_MAKER = "DECISION_MAKER"
    POLICY_REVIEWER = "POLICY_REVIEWER"
    BUDGET_OWNER = "BUDGET_OWNER"
    PROCUREMENT = "PROCUREMENT"
    CARDHOLDER = "CARDHOLDER"
    IT_OPERATIONS = "IT_OPERATIONS"
    AUDITOR = "AUDITOR"
    SELLER_EDITOR = "SELLER_EDITOR"
    SELLER_REVIEWER = "SELLER_REVIEWER"
    PLATFORM_OPERATOR = "PLATFORM_OPERATOR"


class UIActionCapability(StringEnum):
    VIEW_DECISION = "VIEW_DECISION"
    EDIT_REQUEST = "EDIT_REQUEST"
    ANSWER_TASK = "ANSWER_TASK"
    VIEW_PRIVATE_COMPANY_FACTS = "VIEW_PRIVATE_COMPANY_FACTS"
    KEEP_OPTION = "KEEP_OPTION"
    ELIMINATE_OPTION = "ELIMINATE_OPTION"
    ASK_VENDOR = "ASK_VENDOR"
    SAVE_OPTION = "SAVE_OPTION"
    REQUEST_EVIDENCE = "REQUEST_EVIDENCE"
    SELECT_PLAN = "SELECT_PLAN"
    ACCEPT_EXCEPTION = "ACCEPT_EXCEPTION"
    APPROVE_POLICY = "APPROVE_POLICY"
    APPROVE_BUDGET = "APPROVE_BUDGET"
    AUTHORIZE_PAYMENT = "AUTHORIZE_PAYMENT"
    EXECUTE_CONFIGURATION = "EXECUTE_CONFIGURATION"
    VERIFY_FULFILLMENT = "VERIFY_FULFILLMENT"
    PROVIDE_OUTCOME = "PROVIDE_OUTCOME"
    EXPORT_AUDIT = "EXPORT_AUDIT"
    EDIT_PRODUCT_EVIDENCE = "EDIT_PRODUCT_EVIDENCE"
    REVIEW_PRODUCT_EVIDENCE = "REVIEW_PRODUCT_EVIDENCE"
    PUBLISH_PRODUCT_EVIDENCE = "PUBLISH_PRODUCT_EVIDENCE"
    SUSPEND_PRODUCT_EVIDENCE = "SUSPEND_PRODUCT_EVIDENCE"


class SellerEvidenceState(StringEnum):
    UNCLAIMED = "UNCLAIMED"
    CLAIM_PENDING = "CLAIM_PENDING"
    CLAIM_DENIED = "CLAIM_DENIED"
    SELLER_DRAFT = "SELLER_DRAFT"
    VALIDATION_CONFLICT = "VALIDATION_CONFLICT"
    IN_REVIEW = "IN_REVIEW"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    PUBLISH_READY = "PUBLISH_READY"
    PUBLISHED = "PUBLISHED"
    SUPERSEDED = "SUPERSEDED"
    PUBLICATION_FAILED = "PUBLICATION_FAILED"


class SellerReviewDecision(StringEnum):
    REQUEST_CHANGES = "REQUEST_CHANGES"
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class SellerExportFormat(StringEnum):
    JSON = "JSON"
    HTML = "HTML"
    REUSABLE_ANSWER = "REUSABLE_ANSWER"


class ResultArtifactType(StringEnum):
    DECISION_RECORD = "DECISION_RECORD"
    CONFIGURATION_CHANGE = "CONFIGURATION_CHANGE"
    CONTRACT_CONFIRMATION = "CONTRACT_CONFIRMATION"
    CANCELLATION_CONFIRMATION = "CANCELLATION_CONFIRMATION"
    ORDER = "ORDER"
    ENTITLEMENT = "ENTITLEMENT"
    MIGRATION_RECORD = "MIGRATION_RECORD"
    STACK_PATCH = "STACK_PATCH"
    OUTCOME_CHECKPOINT = "OUTCOME_CHECKPOINT"


class StackRisk(StringEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

    @property
    def rank(self) -> int:
        return {
            StackRisk.LOW: 0,
            StackRisk.MEDIUM: 1,
            StackRisk.HIGH: 2,
            StackRisk.CRITICAL: 3,
        }[self]


class TruthValue(StringEnum):
    TRUE = "TRUE"
    FALSE = "FALSE"
    UNKNOWN = "UNKNOWN"
    CONFLICT = "CONFLICT"
    UNRESOLVED = "UNRESOLVED"


class RuleOperator(StringEnum):
    EQ = "eq"
    NEQ = "neq"
    IN = "in"
    NOT_IN = "not_in"
    CONTAINS = "contains"
    CONTAINS_ALL = "contains_all"
    GTE = "gte"
    LTE = "lte"
    GT = "gt"
    LT = "lt"
    EXISTS = "exists"
    DATE_BEFORE = "date_before"
    DATE_ON_OR_BEFORE = "date_on_or_before"
    DATE_AFTER = "date_after"
    DATE_ON_OR_AFTER = "date_on_or_after"


class ProductInstanceState(StringEnum):
    PROPOSED = "proposed"
    CONTRACTED = "contracted"
    PROVISIONED = "provisioned"
    DEPLOYING = "deploying"
    ACTIVE = "active"
    DEGRADED = "degraded"
    RETIRING = "retiring"
    CANCELLED = "cancelled"


class StackPatchStatus(StringEnum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    APPLYING = "APPLYING"
    APPLIED = "APPLIED"
    CONFLICT = "CONFLICT"
    FAILED = "FAILED"
    COMPENSATING_PATCH = "COMPENSATING_PATCH"
