-- 01_bootstrap.sql — Roles, warehouse, resource monitor, database, schemas, and grants
-- Run as ACCOUNTADMIN. Idempotent.

USE ROLE ACCOUNTADMIN;

-- ============================================================
-- ROLES
-- ============================================================
CREATE ROLE IF NOT EXISTS SIRA_SF_BUILD_ROLE
  COMMENT = 'SIRA hackathon build-time role. Creates objects, not used at runtime.';

CREATE ROLE IF NOT EXISTS SIRA_SF_APP_ROLE
  COMMENT = 'SIRA hackathon runtime least-privilege role.';

-- Grant roles to current user for session use
GRANT ROLE SIRA_SF_BUILD_ROLE TO ROLE ACCOUNTADMIN;
GRANT ROLE SIRA_SF_APP_ROLE   TO ROLE ACCOUNTADMIN;

-- ============================================================
-- WAREHOUSE
-- ============================================================
CREATE WAREHOUSE IF NOT EXISTS SIRA_HACK_XS_WH
  WAREHOUSE_SIZE       = 'X-SMALL'
  AUTO_SUSPEND         = 60
  AUTO_RESUME          = TRUE
  MIN_CLUSTER_COUNT    = 1
  MAX_CLUSTER_COUNT    = 1
  INITIALLY_SUSPENDED  = TRUE
  COMMENT              = 'SIRA hackathon compute. X-Small, 60s suspend.';

-- ============================================================
-- RESOURCE MONITOR
-- ============================================================
CREATE OR REPLACE RESOURCE MONITOR SIRA_HACK_WH_MONITOR
  WITH CREDIT_QUOTA = 10
       FREQUENCY    = DAILY
       START_TIMESTAMP = IMMEDIATELY
       TRIGGERS
         ON 25 PERCENT DO NOTIFY
         ON 50 PERCENT DO NOTIFY
         ON 75 PERCENT DO NOTIFY
         ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE SIRA_HACK_XS_WH SET RESOURCE_MONITOR = SIRA_HACK_WH_MONITOR;

-- ============================================================
-- DATABASE AND SCHEMAS
-- ============================================================
CREATE DATABASE IF NOT EXISTS SIRA_HACKATHON
  COMMENT = 'SIRA + SEIL Snowflake evidence and decision plane.';

USE DATABASE SIRA_HACKATHON;

CREATE SCHEMA IF NOT EXISTS GOVERNED
  COMMENT = 'Buyer/catalog governed structured facts.';

CREATE SCHEMA IF NOT EXISTS EVIDENCE
  COMMENT = 'Seller documents, chunks, claims, and search.';

CREATE SCHEMA IF NOT EXISTS DECISION
  COMMENT = 'Decision execution, citations, approval, and audit.';

CREATE SCHEMA IF NOT EXISTS AGENT_APP
  COMMENT = 'Reserved for P1 Cortex Agent and Streamlit.';

-- ============================================================
-- GRANTS TO BUILD ROLE
-- ============================================================
GRANT USAGE   ON WAREHOUSE SIRA_HACK_XS_WH TO ROLE SIRA_SF_BUILD_ROLE;
GRANT OPERATE ON WAREHOUSE SIRA_HACK_XS_WH TO ROLE SIRA_SF_BUILD_ROLE;

GRANT OWNERSHIP ON DATABASE SIRA_HACKATHON       TO ROLE SIRA_SF_BUILD_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA   SIRA_HACKATHON.GOVERNED  TO ROLE SIRA_SF_BUILD_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA   SIRA_HACKATHON.EVIDENCE  TO ROLE SIRA_SF_BUILD_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA   SIRA_HACKATHON.DECISION  TO ROLE SIRA_SF_BUILD_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA   SIRA_HACKATHON.AGENT_APP TO ROLE SIRA_SF_BUILD_ROLE COPY CURRENT GRANTS;

GRANT CREATE STAGE            ON SCHEMA SIRA_HACKATHON.EVIDENCE  TO ROLE SIRA_SF_BUILD_ROLE;
GRANT CREATE TABLE            ON SCHEMA SIRA_HACKATHON.EVIDENCE  TO ROLE SIRA_SF_BUILD_ROLE;
GRANT CREATE VIEW             ON SCHEMA SIRA_HACKATHON.EVIDENCE  TO ROLE SIRA_SF_BUILD_ROLE;
GRANT CREATE STAGE            ON SCHEMA SIRA_HACKATHON.DECISION  TO ROLE SIRA_SF_BUILD_ROLE;
GRANT CREATE TABLE            ON SCHEMA SIRA_HACKATHON.DECISION  TO ROLE SIRA_SF_BUILD_ROLE;
GRANT CREATE VIEW             ON SCHEMA SIRA_HACKATHON.DECISION  TO ROLE SIRA_SF_BUILD_ROLE;
GRANT CREATE PROCEDURE        ON SCHEMA SIRA_HACKATHON.DECISION  TO ROLE SIRA_SF_BUILD_ROLE;

-- Cortex Search requires database-level privilege
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA SIRA_HACKATHON.EVIDENCE TO ROLE SIRA_SF_BUILD_ROLE;

-- ============================================================
-- GRANTS TO APP ROLE (runtime least-privilege)
-- ============================================================
GRANT USAGE ON WAREHOUSE SIRA_HACK_XS_WH      TO ROLE SIRA_SF_APP_ROLE;
GRANT USAGE ON DATABASE  SIRA_HACKATHON        TO ROLE SIRA_SF_APP_ROLE;
GRANT USAGE ON SCHEMA    SIRA_HACKATHON.GOVERNED   TO ROLE SIRA_SF_APP_ROLE;
GRANT USAGE ON SCHEMA    SIRA_HACKATHON.EVIDENCE   TO ROLE SIRA_SF_APP_ROLE;
GRANT USAGE ON SCHEMA    SIRA_HACKATHON.DECISION   TO ROLE SIRA_SF_APP_ROLE;

-- App role can read governed data
GRANT SELECT ON ALL TABLES IN SCHEMA SIRA_HACKATHON.GOVERNED TO ROLE SIRA_SF_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SIRA_HACKATHON.GOVERNED TO ROLE SIRA_SF_APP_ROLE;

-- App role can read evidence
GRANT SELECT ON ALL TABLES IN SCHEMA SIRA_HACKATHON.EVIDENCE TO ROLE SIRA_SF_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SIRA_HACKATHON.EVIDENCE TO ROLE SIRA_SF_APP_ROLE;

-- App role can insert into decision tables but not update/delete approval
GRANT SELECT ON ALL TABLES IN SCHEMA SIRA_HACKATHON.DECISION TO ROLE SIRA_SF_APP_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SIRA_HACKATHON.DECISION TO ROLE SIRA_SF_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA SIRA_HACKATHON.DECISION TO ROLE SIRA_SF_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SIRA_HACKATHON.DECISION TO ROLE SIRA_SF_APP_ROLE;
GRANT INSERT ON ALL TABLES IN SCHEMA SIRA_HACKATHON.DECISION TO ROLE SIRA_SF_APP_ROLE;
GRANT INSERT ON FUTURE TABLES IN SCHEMA SIRA_HACKATHON.DECISION TO ROLE SIRA_SF_APP_ROLE;

-- Procedure usage is granted in 06_snowpark_evaluator.sql after it exists.
