-- 10_runtime_identity.sql — least-privilege API identity
-- Replace <RSA_PUBLIC_KEY_BODY> with the base64 body of an RSA public key.

USE ROLE ACCOUNTADMIN;

CREATE USER IF NOT EXISTS SIRA_APP_USER
  TYPE = SERVICE
  DEFAULT_ROLE = SIRA_SF_APP_ROLE
  DEFAULT_WAREHOUSE = SIRA_HACK_XS_WH
  RSA_PUBLIC_KEY = '<RSA_PUBLIC_KEY_BODY>'
  COMMENT = 'Key-pair identity for the SIRA FastAPI service';

ALTER USER SIRA_APP_USER SET
  RSA_PUBLIC_KEY = '<RSA_PUBLIC_KEY_BODY>'
  DEFAULT_ROLE = SIRA_SF_APP_ROLE
  DEFAULT_WAREHOUSE = SIRA_HACK_XS_WH;

GRANT ROLE SIRA_SF_APP_ROLE TO USER SIRA_APP_USER;
