"""add decision graph records

Revision ID: 23a8fff461fe
Revises: d7a1c4e9b203
Create Date: 2026-08-02 05:29:33.845207
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "23a8fff461fe"
down_revision: str | None = "d7a1c4e9b203"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = (
    "evaluation_pipeline_versions",
    "evaluation_runs",
    "counterfactual_records",
    "discovery_runs",
    "evaluation_solution_plans",
    "evidence_assessments",
    "action_runs",
    "candidate_set_members",
    "decision_gate_results",
    "identity_merges",
    "robustness_frontiers",
    "score_bounds",
    "score_components",
    "solution_plan_components",
    "result_artifacts",
)


def _enable_tenant_rls() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    for table_name in TENANT_TABLES:
        op.execute(sa.text(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY'))
        op.execute(sa.text(f'ALTER TABLE "{table_name}" FORCE ROW LEVEL SECURITY'))
        op.execute(
            sa.text(
                f'CREATE POLICY tenant_isolation ON "{table_name}" '
                "USING (organization_id = current_setting('app.organization_id', true)) "
                "WITH CHECK (organization_id = current_setting('app.organization_id', true))"
            )
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_pipeline_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("pipeline_version", sa.String(length=80), nullable=False),
        sa.Column("engine_version", sa.String(length=80), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=80), nullable=False),
        sa.Column("normalization_version", sa.String(length=80), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=False),
        sa.Column("risk_rule_set_version", sa.String(length=80), nullable=False),
        sa.Column("content_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "content_hash", name="uq_evaluation_pipeline_content_hash"
        ),
        sa.UniqueConstraint(
            "organization_id", "pipeline_version", name="uq_evaluation_pipeline_version"
        ),
    )
    op.create_index(
        op.f("ix_evaluation_pipeline_versions_organization_id"),
        "evaluation_pipeline_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_request_id", sa.String(length=64), nullable=False),
        sa.Column("purchase_brief_id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=True),
        sa.Column("evaluation_pipeline_version_id", sa.String(length=64), nullable=False),
        sa.Column("run_kind", sa.String(length=24), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_version", sa.String(length=80), nullable=False),
        sa.Column("company_profile_version", sa.String(length=80), nullable=False),
        sa.Column("stackfile_version", sa.String(length=80), nullable=False),
        sa.Column("registry_version", sa.String(length=80), nullable=False),
        sa.Column("candidate_set_version", sa.String(length=80), nullable=False),
        sa.Column("pack_set_version", sa.String(length=80), nullable=False),
        sa.Column("offer_set_version", sa.String(length=80), nullable=False),
        sa.Column("quote_set_version", sa.String(length=80), nullable=False),
        sa.Column("taxonomy_version", sa.String(length=80), nullable=False),
        sa.Column("normalization_version", sa.String(length=80), nullable=False),
        sa.Column("policy_version", sa.String(length=80), nullable=False),
        sa.Column("fx_version", sa.String(length=80), nullable=False),
        sa.Column("pipeline_version", sa.String(length=80), nullable=False),
        sa.Column("engine_version", sa.String(length=80), nullable=False),
        sa.Column("input_payload_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "input_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("evaluation_payload_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "evaluation_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("selected_solution_plan_id", sa.String(length=64), nullable=True),
        sa.Column("rank_stability", sa.String(length=24), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rank_stability IN ('STABLE','UNSTABLE','UNDETERMINED')",
            name="ck_evaluation_rank_stability",
        ),
        sa.CheckConstraint(
            "run_kind IN ('BASE','GENERIC','COUNTERFACTUAL','REPLAY')",
            name="ck_evaluation_run_kind",
        ),
        sa.ForeignKeyConstraint(["decision_id"], ["decision_records.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["evaluation_pipeline_version_id"],
            ["evaluation_pipeline_versions.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_brief_id"], ["purchase_brief_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"], ["purchase_requests.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "evaluation_payload_hash", name="uq_evaluation_payload_hash"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "purchase_request_id",
            "input_payload_hash",
            name="uq_evaluation_run_input",
        ),
    )
    op.create_index(
        "ix_evaluation_runs_decision_id", "evaluation_runs", ["decision_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_runs_organization_id"),
        "evaluation_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_evaluation_runs_request_evaluated",
        "evaluation_runs",
        ["purchase_request_id", "evaluated_at"],
        unique=False,
    )
    op.create_table(
        "counterfactual_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=True),
        sa.Column("outcome", sa.String(length=48), nullable=False),
        sa.Column(
            "removed_fact_ids",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "alternative_fact_id_sets",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("tested_limit", sa.Integer(), nullable=False),
        sa.Column("base_evaluation_payload_hash", sa.String(length=80), nullable=False),
        sa.Column("alternate_evaluation_payload_hash", sa.String(length=80), nullable=True),
        sa.Column("generic_evaluation_payload_hash", sa.String(length=80), nullable=False),
        sa.Column("base_selected_solution_plan_id", sa.String(length=64), nullable=True),
        sa.Column("alternate_selected_solution_plan_id", sa.String(length=64), nullable=True),
        sa.Column("generic_selected_solution_plan_id", sa.String(length=64), nullable=True),
        sa.Column(
            "changed_gate_ids",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("record_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(outcome = 'WINNER_CHANGED' AND alternate_evaluation_payload_hash IS NOT NULL) OR (outcome = 'NO_SMALL_COUNTERFACTUAL_FOUND' AND alternate_evaluation_payload_hash IS NULL)",
            name="ck_counterfactual_alternate_hash",
        ),
        sa.CheckConstraint(
            "outcome IN ('WINNER_CHANGED','NO_SMALL_COUNTERFACTUAL_FOUND')",
            name="ck_counterfactual_outcome",
        ),
        sa.CheckConstraint(
            "alternate_evaluation_payload_hash IS NULL OR alternate_evaluation_payload_hash <> base_evaluation_payload_hash",
            name="ck_counterfactual_distinct_alternate_hash",
        ),
        sa.CheckConstraint("tested_limit BETWEEN 1 AND 3", name="ck_counterfactual_tested_limit"),
        sa.ForeignKeyConstraint(["decision_id"], ["decision_records.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["organization_id", "alternate_evaluation_payload_hash"],
            ["evaluation_runs.organization_id", "evaluation_runs.evaluation_payload_hash"],
            name="fk_counterfactual_alternate_evaluation_hash",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "base_evaluation_payload_hash"],
            ["evaluation_runs.organization_id", "evaluation_runs.evaluation_payload_hash"],
            name="fk_counterfactual_base_evaluation_hash",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "generic_evaluation_payload_hash"],
            ["evaluation_runs.organization_id", "evaluation_runs.evaluation_payload_hash"],
            name="fk_counterfactual_generic_evaluation_hash",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "record_hash", name="uq_counterfactual_record_hash"),
    )
    op.create_index(
        "ix_counterfactual_records_base_hash",
        "counterfactual_records",
        ["base_evaluation_payload_hash"],
        unique=False,
    )
    op.create_index(
        "ix_counterfactual_records_decision",
        "counterfactual_records",
        ["decision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_counterfactual_records_organization_id"),
        "counterfactual_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "discovery_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("evaluation_run_id", sa.String(length=64), nullable=False),
        sa.Column("candidate_set_hash", sa.String(length=80), nullable=False),
        sa.Column("output_hash", sa.String(length=80), nullable=False),
        sa.Column("raw_record_count", sa.Integer(), nullable=False),
        sa.Column("canonical_product_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("generated_solution_plan_count", sa.Integer(), nullable=False),
        sa.Column("excluded_count", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "raw_record_count >= 0 AND canonical_product_count >= 0 AND duplicate_count >= 0 AND generated_solution_plan_count >= 0 AND excluded_count >= 0",
            name="ck_discovery_counts_nonnegative",
        ),
        sa.ForeignKeyConstraint(["evaluation_run_id"], ["evaluation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "evaluation_run_id", name="uq_discovery_evaluation"),
    )
    op.create_index(
        op.f("ix_discovery_runs_organization_id"),
        "discovery_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "evaluation_solution_plans",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("evaluation_run_id", sa.String(length=64), nullable=False),
        sa.Column("solution_plan_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("component_hash", sa.String(length=80), nullable=False),
        sa.Column("plan_hash", sa.String(length=80), nullable=False),
        sa.Column("construction_lifecycle", sa.String(length=32), nullable=False),
        sa.Column("lifecycle", sa.String(length=32), nullable=False),
        sa.Column("candidate_status", sa.String(length=32), nullable=False),
        sa.Column("primary_reason_code", sa.String(length=100), nullable=True),
        sa.Column("rank_position", sa.Integer(), nullable=True),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("ordering_frontier_member", sa.Boolean(), nullable=False),
        sa.Column("resolution_frontier_member", sa.Boolean(), nullable=False),
        sa.Column("quote_required", sa.Boolean(), nullable=False),
        sa.Column("quote_policy_reason", sa.String(length=100), nullable=False),
        sa.Column("permitted_resolution", sa.String(length=200), nullable=True),
        sa.Column("autonomous_execution_allowed", sa.Boolean(), nullable=False),
        sa.Column(
            "stable_action_ids",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('REUSE_EXISTING','CONFIGURE_EXISTING','NO_ACTION','BUY','RENEW','RESIZE','REPLACE','CONSOLIDATE','CANCEL')",
            name="ck_evaluation_plan_action",
        ),
        sa.CheckConstraint(
            "construction_lifecycle IN ('CANDIDATE','RESOLUTION_PENDING','EXECUTABLE','BLOCKED')",
            name="ck_evaluation_plan_construction_lifecycle",
        ),
        sa.CheckConstraint(
            "lifecycle IN ('CANDIDATE','RESOLUTION_PENDING','EXECUTABLE','BLOCKED')",
            name="ck_evaluation_plan_lifecycle",
        ),
        sa.CheckConstraint(
            "candidate_status IN ('ELIGIBLE','ELIGIBLE_WITH_EXCEPTION','CONDITIONAL','SIRA_INELIGIBLE','SEIL_PASS','UNAVAILABLE','STALE_EVIDENCE','INSUFFICIENT_EVIDENCE','CONFLICTING_EVIDENCE','AUTHORITY_REQUIRED','ADVISORY_ONLY')",
            name="ck_evaluation_plan_candidate_status",
        ),
        sa.CheckConstraint(
            "rank_position IS NULL OR rank_position >= 1", name="ck_evaluation_plan_rank_positive"
        ),
        sa.ForeignKeyConstraint(["evaluation_run_id"], ["evaluation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "evaluation_run_id", "plan_hash", name="uq_evaluation_plan_hash"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "evaluation_run_id",
            "solution_plan_id",
            name="uq_evaluation_solution_plan",
        ),
    )
    op.create_index(
        op.f("ix_evaluation_solution_plans_organization_id"),
        "evaluation_solution_plans",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_evaluation_solution_plans_rank",
        "evaluation_solution_plans",
        ["evaluation_run_id", "rank_position"],
        unique=False,
    )
    op.create_table(
        "evidence_assessments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("evaluation_run_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_id", sa.String(length=100), nullable=False),
        sa.Column("source_record_id", sa.String(length=128), nullable=False),
        sa.Column("field", sa.String(length=160), nullable=False),
        sa.Column(
            "supported_criterion_ids",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("source_allowed", sa.Boolean(), nullable=False),
        sa.Column("method_allowed", sa.Boolean(), nullable=False),
        sa.Column("scope_match", sa.Boolean(), nullable=False),
        sa.Column("reconstructable", sa.Boolean(), nullable=False),
        sa.Column("freshness_current", sa.Boolean(), nullable=True),
        sa.Column("disputed", sa.Boolean(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("age_lower_numerator", sa.BigInteger(), nullable=True),
        sa.Column("age_lower_denominator", sa.BigInteger(), nullable=True),
        sa.Column("age_upper_numerator", sa.BigInteger(), nullable=True),
        sa.Column("age_upper_denominator", sa.BigInteger(), nullable=True),
        sa.Column(
            "reason_codes",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("assessment_hash", sa.String(length=80), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('ACCEPTABLE','UNKNOWN','STALE','CONFLICT')",
            name="ck_evidence_assessment_state",
        ),
        sa.CheckConstraint(
            "(age_lower_numerator IS NULL AND age_lower_denominator IS NULL AND age_upper_numerator IS NULL AND age_upper_denominator IS NULL) OR (age_lower_numerator IS NOT NULL AND age_lower_denominator IS NOT NULL AND age_upper_numerator IS NOT NULL AND age_upper_denominator IS NOT NULL)",
            name="ck_evidence_age_bounds_complete",
        ),
        sa.CheckConstraint(
            "age_lower_denominator IS NULL OR age_lower_denominator > 0",
            name="ck_evidence_age_lower_denominator_positive",
        ),
        sa.CheckConstraint(
            "age_upper_denominator IS NULL OR age_upper_denominator > 0",
            name="ck_evidence_age_upper_denominator_positive",
        ),
        sa.ForeignKeyConstraint(["evaluation_run_id"], ["evaluation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "evaluation_run_id",
            "evidence_id",
            "field",
            name="uq_evidence_assessment",
        ),
    )
    op.create_index(
        "ix_evidence_assessments_evaluation_field",
        "evidence_assessments",
        ["evaluation_run_id", "field"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_assessments_organization_id"),
        "evidence_assessments",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "action_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("solution_plan_record_id", sa.String(length=64), nullable=False),
        sa.Column("solution_plan_id", sa.String(length=64), nullable=False),
        sa.Column("purchase_intent_id", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_checkpoint", sa.String(length=100), nullable=True),
        sa.Column("last_successful_checkpoint", sa.String(length=100), nullable=True),
        sa.Column("owner_role", sa.String(length=80), nullable=False),
        sa.Column(
            "blocking_task",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "recovery_action",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("safe_to_leave", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("run_hash", sa.String(length=80), nullable=False),
        sa.Column("supersedes_id", sa.String(length=64), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('REUSE_EXISTING','CONFIGURE_EXISTING','NO_ACTION','BUY','RENEW','RESIZE','REPLACE','CONSOLIDATE','CANCEL')",
            name="ck_action_run_action",
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED','RUNNING','WAITING_FOR_HUMAN','RETRYABLE_ERROR','UNCERTAIN','COMPLETED','FAILED_FINAL')",
            name="ck_action_run_status",
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= started_at",
            name="ck_action_run_completion_order",
        ),
        sa.CheckConstraint(
            "status NOT IN ('COMPLETED','FAILED_FINAL') OR completed_at IS NOT NULL",
            name="ck_action_run_terminal_completion",
        ),
        sa.ForeignKeyConstraint(["decision_id"], ["decision_records.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_intent_id"], ["purchase_intents.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["solution_plan_record_id"], ["evaluation_solution_plans.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["supersedes_id"], ["action_runs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "decision_id",
            "solution_plan_record_id",
            name="uq_action_run_decision_plan",
        ),
        sa.UniqueConstraint("organization_id", "run_hash", name="uq_action_run_hash"),
    )
    op.create_index(
        "ix_action_runs_decision_status", "action_runs", ["decision_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_action_runs_organization_id"), "action_runs", ["organization_id"], unique=False
    )
    op.create_table(
        "candidate_set_members",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("discovery_run_id", sa.String(length=64), nullable=False),
        sa.Column("canonical_identity_id", sa.String(length=128), nullable=False),
        sa.Column("source_record_id", sa.String(length=128), nullable=False),
        sa.Column("member_kind", sa.String(length=24), nullable=False),
        sa.Column("disposition", sa.String(length=24), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("pack_id", sa.String(length=100), nullable=True),
        sa.Column("pack_version", sa.Integer(), nullable=True),
        sa.Column("offer_id", sa.String(length=100), nullable=True),
        sa.Column("offer_version", sa.Integer(), nullable=True),
        sa.Column("current_action_id", sa.String(length=100), nullable=True),
        sa.Column("member_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "disposition IN ('INCLUDED','EXCLUDED','DEDUPLICATED')",
            name="ck_candidate_set_disposition",
        ),
        sa.CheckConstraint(
            "member_kind IN ('PACK','CURRENT_STACK','CONTRACT_ACTION','NO_ACTION')",
            name="ck_candidate_set_member_kind",
        ),
        sa.CheckConstraint(
            "offer_version IS NULL OR offer_version >= 1",
            name="ck_candidate_set_offer_version_positive",
        ),
        sa.CheckConstraint("ordinal >= 0", name="ck_candidate_set_ordinal_nonnegative"),
        sa.CheckConstraint(
            "pack_version IS NULL OR pack_version >= 1",
            name="ck_candidate_set_pack_version_positive",
        ),
        sa.ForeignKeyConstraint(["discovery_run_id"], ["discovery_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "discovery_run_id", "ordinal", name="uq_candidate_set_ordinal"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "discovery_run_id",
            "source_record_id",
            name="uq_candidate_set_source",
        ),
    )
    op.create_index(
        "ix_candidate_set_members_identity",
        "candidate_set_members",
        ["discovery_run_id", "canonical_identity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_set_members_organization_id"),
        "candidate_set_members",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "decision_gate_results",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("evaluation_run_id", sa.String(length=64), nullable=False),
        sa.Column("solution_plan_record_id", sa.String(length=64), nullable=False),
        sa.Column("gate_id", sa.String(length=100), nullable=False),
        sa.Column("truth", sa.String(length=16), nullable=False),
        sa.Column("derived_status", sa.String(length=32), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "reason_codes",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "evaluated_predicates",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "source_fact_ids",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("permitted_resolution", sa.String(length=200), nullable=True),
        sa.Column("overridable", sa.Boolean(), nullable=False),
        sa.Column("result_hash", sa.String(length=80), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "truth IN ('TRUE','FALSE','UNKNOWN','CONFLICT')", name="ck_decision_gate_truth"
        ),
        sa.CheckConstraint(
            "derived_status IS NULL OR derived_status IN ('ELIGIBLE','ELIGIBLE_WITH_EXCEPTION','CONDITIONAL','SIRA_INELIGIBLE','SEIL_PASS','UNAVAILABLE','STALE_EVIDENCE','INSUFFICIENT_EVIDENCE','CONFLICTING_EVIDENCE','AUTHORITY_REQUIRED','ADVISORY_ONLY')",
            name="ck_decision_gate_derived_status",
        ),
        sa.ForeignKeyConstraint(["evaluation_run_id"], ["evaluation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["solution_plan_record_id"], ["evaluation_solution_plans.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "solution_plan_record_id", "gate_id", name="uq_decision_gate_result"
        ),
    )
    op.create_index(
        "ix_decision_gate_results_evaluation",
        "decision_gate_results",
        ["evaluation_run_id", "gate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_gate_results_organization_id"),
        "decision_gate_results",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "identity_merges",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("discovery_run_id", sa.String(length=64), nullable=False),
        sa.Column("canonical_identity_id", sa.String(length=128), nullable=False),
        sa.Column("merged_record_id", sa.String(length=128), nullable=False),
        sa.Column(
            "reason_codes",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("merge_hash", sa.String(length=80), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["discovery_run_id"], ["discovery_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "discovery_run_id", "merge_hash", name="uq_identity_merge_hash"
        ),
        sa.UniqueConstraint(
            "organization_id",
            "discovery_run_id",
            "merged_record_id",
            name="uq_identity_merge_record",
        ),
    )
    op.create_index(
        "ix_identity_merges_canonical",
        "identity_merges",
        ["discovery_run_id", "canonical_identity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_identity_merges_organization_id"),
        "identity_merges",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "robustness_frontiers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("evaluation_run_id", sa.String(length=64), nullable=False),
        sa.Column("solution_plan_record_id", sa.String(length=64), nullable=False),
        sa.Column("frontier_kind", sa.String(length=32), nullable=False),
        sa.Column("decision_rank_stability", sa.String(length=24), nullable=False),
        sa.Column("member", sa.Boolean(), nullable=False),
        sa.Column("can_beat_selected", sa.Boolean(), nullable=True),
        sa.Column("permitted_resolution", sa.String(length=200), nullable=True),
        sa.Column(
            "frontier_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("frontier_hash", sa.String(length=80), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision_rank_stability IN ('STABLE','UNSTABLE','UNDETERMINED')",
            name="ck_robustness_rank_stability",
        ),
        sa.CheckConstraint(
            "frontier_kind IN ('ORDERING','RESOLUTION','BOUND_UNAVAILABLE')",
            name="ck_robustness_frontier_kind",
        ),
        sa.ForeignKeyConstraint(["evaluation_run_id"], ["evaluation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["solution_plan_record_id"], ["evaluation_solution_plans.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "solution_plan_record_id",
            "frontier_kind",
            name="uq_robustness_frontier_kind",
        ),
    )
    op.create_index(
        "ix_robustness_frontiers_evaluation",
        "robustness_frontiers",
        ["evaluation_run_id", "frontier_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_robustness_frontiers_organization_id"),
        "robustness_frontiers",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "score_bounds",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("evaluation_run_id", sa.String(length=64), nullable=False),
        sa.Column("solution_plan_record_id", sa.String(length=64), nullable=False),
        sa.Column("dimension", sa.String(length=48), nullable=False),
        sa.Column("bound_status", sa.String(length=24), nullable=False),
        sa.Column("value_kind", sa.String(length=24), nullable=False),
        sa.Column("lower_numerator", sa.BigInteger(), nullable=True),
        sa.Column("lower_denominator", sa.BigInteger(), nullable=True),
        sa.Column("base_numerator", sa.BigInteger(), nullable=True),
        sa.Column("base_denominator", sa.BigInteger(), nullable=True),
        sa.Column("upper_numerator", sa.BigInteger(), nullable=True),
        sa.Column("upper_denominator", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("unavailable_reason", sa.String(length=160), nullable=True),
        sa.Column(
            "calculation_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("bound_hash", sa.String(length=80), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(bound_status = 'AVAILABLE' AND lower_numerator IS NOT NULL AND lower_denominator IS NOT NULL AND base_numerator IS NOT NULL AND base_denominator IS NOT NULL AND upper_numerator IS NOT NULL AND upper_denominator IS NOT NULL AND unavailable_reason IS NULL) OR (bound_status = 'BOUND_UNAVAILABLE' AND unavailable_reason IS NOT NULL)",
            name="ck_score_bound_availability",
        ),
        sa.CheckConstraint(
            "bound_status IN ('AVAILABLE','BOUND_UNAVAILABLE')", name="ck_score_bound_status"
        ),
        sa.CheckConstraint(
            "dimension IN ('PREFERENCE','STACK_RISK','TCO','DECISION_MATERIAL_COVERAGE','EVIDENCE_AGE','HARD_COVERAGE','UNIVERSE_COVERAGE')",
            name="ck_score_bound_dimension",
        ),
        sa.CheckConstraint(
            "value_kind IN ('RATIO','RISK_ORDINAL','MONEY','COUNT')",
            name="ck_score_bound_value_kind",
        ),
        sa.CheckConstraint(
            "(lower_denominator IS NULL OR lower_denominator > 0) AND (base_denominator IS NULL OR base_denominator > 0) AND (upper_denominator IS NULL OR upper_denominator > 0)",
            name="ck_score_bound_denominators_positive",
        ),
        sa.CheckConstraint(
            "currency IS NULL OR currency = upper(currency)", name="ck_score_bound_currency_upper"
        ),
        sa.CheckConstraint(
            "(value_kind = 'MONEY' AND currency IS NOT NULL) OR (value_kind <> 'MONEY' AND currency IS NULL)",
            name="ck_score_bound_currency_kind",
        ),
        sa.CheckConstraint(
            "value_kind <> 'RISK_ORDINAL' OR bound_status = 'BOUND_UNAVAILABLE' OR (lower_denominator = 1 AND base_denominator = 1 AND upper_denominator = 1 AND lower_numerator BETWEEN 0 AND 3 AND base_numerator BETWEEN 0 AND 3 AND upper_numerator BETWEEN 0 AND 3)",
            name="ck_score_bound_risk_ordinal",
        ),
        sa.ForeignKeyConstraint(["evaluation_run_id"], ["evaluation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["solution_plan_record_id"], ["evaluation_solution_plans.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "solution_plan_record_id",
            "dimension",
            name="uq_score_bound_dimension",
        ),
    )
    op.create_index(
        "ix_score_bounds_evaluation_dimension",
        "score_bounds",
        ["evaluation_run_id", "dimension"],
        unique=False,
    )
    op.create_index(
        op.f("ix_score_bounds_organization_id"), "score_bounds", ["organization_id"], unique=False
    )
    op.create_table(
        "score_components",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("evaluation_run_id", sa.String(length=64), nullable=False),
        sa.Column("solution_plan_record_id", sa.String(length=64), nullable=False),
        sa.Column("criterion_id", sa.String(length=100), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("coverage_weight", sa.Integer(), nullable=False),
        sa.Column("conservative_satisfaction_numerator", sa.BigInteger(), nullable=False),
        sa.Column("conservative_satisfaction_denominator", sa.BigInteger(), nullable=False),
        sa.Column("optimistic_satisfaction_numerator", sa.BigInteger(), nullable=False),
        sa.Column("optimistic_satisfaction_denominator", sa.BigInteger(), nullable=False),
        sa.Column("contribution_conservative_numerator", sa.BigInteger(), nullable=False),
        sa.Column("contribution_conservative_denominator", sa.BigInteger(), nullable=False),
        sa.Column("contribution_optimistic_numerator", sa.BigInteger(), nullable=False),
        sa.Column("contribution_optimistic_denominator", sa.BigInteger(), nullable=False),
        sa.Column(
            "evidence_ids",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("evidence_state", sa.String(length=24), nullable=False),
        sa.Column("prior_label", sa.String(length=120), nullable=True),
        sa.Column("input_hash", sa.String(length=80), nullable=False),
        sa.Column("component_hash", sa.String(length=80), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "evidence_state IN ('ACCEPTABLE','UNKNOWN','STALE','CONFLICT')",
            name="ck_score_component_evidence_state",
        ),
        sa.CheckConstraint(
            "conservative_satisfaction_denominator > 0 AND optimistic_satisfaction_denominator > 0 AND contribution_conservative_denominator > 0 AND contribution_optimistic_denominator > 0",
            name="ck_score_component_denominators_positive",
        ),
        sa.CheckConstraint(
            "conservative_satisfaction_numerator BETWEEN 0 AND conservative_satisfaction_denominator AND optimistic_satisfaction_numerator BETWEEN 0 AND optimistic_satisfaction_denominator",
            name="ck_score_component_satisfaction_unit_interval",
        ),
        sa.CheckConstraint(
            "coverage_weight BETWEEN 1 AND 5", name="ck_score_component_coverage_weight"
        ),
        sa.CheckConstraint("weight BETWEEN 1 AND 5", name="ck_score_component_weight"),
        sa.ForeignKeyConstraint(["evaluation_run_id"], ["evaluation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["solution_plan_record_id"], ["evaluation_solution_plans.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "solution_plan_record_id",
            "criterion_id",
            name="uq_score_component_criterion",
        ),
    )
    op.create_index(
        "ix_score_components_evaluation",
        "score_components",
        ["evaluation_run_id", "criterion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_score_components_organization_id"),
        "score_components",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "solution_plan_components",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("evaluation_run_id", sa.String(length=64), nullable=False),
        sa.Column("solution_plan_record_id", sa.String(length=64), nullable=False),
        sa.Column("component_id", sa.String(length=100), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("source_record_id", sa.String(length=128), nullable=True),
        sa.Column("component_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('REUSE_EXISTING','CONFIGURE_EXISTING','NO_ACTION','BUY','RENEW','RESIZE','REPLACE','CONSOLIDATE','CANCEL')",
            name="ck_solution_plan_component_action",
        ),
        sa.CheckConstraint(
            "source_type IN ('PACK','CURRENT_STACK','CONTRACT_ACTION','NO_ACTION')",
            name="ck_solution_plan_component_source_type",
        ),
        sa.CheckConstraint("ordinal >= 0", name="ck_solution_plan_component_ordinal_nonnegative"),
        sa.ForeignKeyConstraint(["evaluation_run_id"], ["evaluation_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["solution_plan_record_id"], ["evaluation_solution_plans.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "solution_plan_record_id",
            "component_id",
            name="uq_solution_plan_component",
        ),
        sa.UniqueConstraint(
            "organization_id",
            "solution_plan_record_id",
            "ordinal",
            name="uq_solution_plan_component_ordinal",
        ),
    )
    op.create_index(
        "ix_solution_plan_components_evaluation",
        "solution_plan_components",
        ["evaluation_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_solution_plan_components_organization_id"),
        "solution_plan_components",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "result_artifacts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("action_run_id", sa.String(length=64), nullable=False),
        sa.Column("artifact_type", sa.String(length=40), nullable=False),
        sa.Column("verification_state", sa.String(length=24), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=True),
        sa.Column("owner_role", sa.String(length=80), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("safe_label", sa.String(length=200), nullable=False),
        sa.Column("href", sa.Text(), nullable=False),
        sa.Column("stack_patch_id", sa.String(length=64), nullable=True),
        sa.Column("receipt_id", sa.String(length=64), nullable=True),
        sa.Column("artifact_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "artifact_type IN ('DECISION_RECORD','CONFIGURATION_CHANGE','CONTRACT_CONFIRMATION','CANCELLATION_CONFIRMATION','ORDER','ENTITLEMENT','MIGRATION_RECORD','STACK_PATCH','OUTCOME_CHECKPOINT')",
            name="ck_result_artifact_type",
        ),
        sa.CheckConstraint(
            "verification_state IN ('PENDING','VERIFIED','FAILED','REVOKED')",
            name="ck_result_artifact_verification_state",
        ),
        sa.CheckConstraint(
            "verified_at IS NULL OR verified_at >= occurred_at",
            name="ck_result_artifact_verification_order",
        ),
        sa.CheckConstraint(
            "verification_state <> 'VERIFIED' OR verified_at IS NOT NULL",
            name="ck_result_artifact_verified_timestamp",
        ),
        sa.ForeignKeyConstraint(["action_run_id"], ["action_runs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["receipt_id"], ["receipts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["stack_patch_id"], ["stack_patches.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "action_run_id", "artifact_hash", name="uq_result_artifact_hash"
        ),
    )
    op.create_index(
        "ix_result_artifacts_action_type",
        "result_artifacts",
        ["action_run_id", "artifact_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_result_artifacts_organization_id"),
        "result_artifacts",
        ["organization_id"],
        unique=False,
    )
    with op.batch_alter_table("requirement_brief_versions") as batch:
        batch.create_unique_constraint(
            "uq_requirement_brief_exact_binding",
            ["organization_id", "id", "version", "content_hash"],
        )
    op.add_column(
        "engagements",
        sa.Column("requirement_brief_id", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "engagements",
        sa.Column("requirement_brief_version", sa.Integer(), nullable=True),
    )
    op.add_column(
        "engagements",
        sa.Column("requirement_brief_hash", sa.String(length=80), nullable=True),
    )
    op.execute(
        sa.text(
            """
            UPDATE engagements
            SET requirement_brief_id = (
                    SELECT brief.id
                    FROM requirement_brief_versions AS brief
                    WHERE brief.organization_id = engagements.organization_id
                      AND brief.purchase_request_id = engagements.purchase_request_id
                    ORDER BY brief.version DESC, brief.id DESC
                    LIMIT 1
                ),
                requirement_brief_version = (
                    SELECT brief.version
                    FROM requirement_brief_versions AS brief
                    WHERE brief.organization_id = engagements.organization_id
                      AND brief.purchase_request_id = engagements.purchase_request_id
                    ORDER BY brief.version DESC, brief.id DESC
                    LIMIT 1
                ),
                requirement_brief_hash = (
                    SELECT brief.content_hash
                    FROM requirement_brief_versions AS brief
                    WHERE brief.organization_id = engagements.organization_id
                      AND brief.purchase_request_id = engagements.purchase_request_id
                    ORDER BY brief.version DESC, brief.id DESC
                    LIMIT 1
                )
            """
        )
    )
    unbound_count = (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT count(*) FROM engagements "
                "WHERE requirement_brief_id IS NULL "
                "OR requirement_brief_version IS NULL "
                "OR requirement_brief_hash IS NULL"
            )
        )
        .scalar_one()
    )
    if unbound_count:
        raise RuntimeError(
            "Cannot bind every engagement to an existing exact Requirement Brief version"
        )
    with op.batch_alter_table("engagements") as batch:
        batch.alter_column(
            "requirement_brief_id", existing_type=sa.String(length=64), nullable=False
        )
        batch.alter_column("requirement_brief_version", existing_type=sa.Integer(), nullable=False)
        batch.alter_column(
            "requirement_brief_hash", existing_type=sa.String(length=80), nullable=False
        )
        batch.create_foreign_key(
            "fk_engagement_exact_requirement_brief",
            "requirement_brief_versions",
            [
                "organization_id",
                "requirement_brief_id",
                "requirement_brief_version",
                "requirement_brief_hash",
            ],
            ["organization_id", "id", "version", "content_hash"],
            ondelete="RESTRICT",
        )
        batch.create_check_constraint(
            "ck_engagement_requirement_brief_version_positive",
            "requirement_brief_version >= 1",
        )
        batch.create_index(
            "ix_engagements_requirement_brief", ["requirement_brief_id"], unique=False
        )
    _enable_tenant_rls()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("engagements") as batch:
        batch.drop_index("ix_engagements_requirement_brief")
        batch.drop_constraint("ck_engagement_requirement_brief_version_positive", type_="check")
        batch.drop_constraint("fk_engagement_exact_requirement_brief", type_="foreignkey")
        batch.drop_column("requirement_brief_hash")
        batch.drop_column("requirement_brief_version")
        batch.drop_column("requirement_brief_id")
    with op.batch_alter_table("requirement_brief_versions") as batch:
        batch.drop_constraint("uq_requirement_brief_exact_binding", type_="unique")
    op.drop_index(op.f("ix_result_artifacts_organization_id"), table_name="result_artifacts")
    op.drop_index("ix_result_artifacts_action_type", table_name="result_artifacts")
    op.drop_table("result_artifacts")
    op.drop_index(
        op.f("ix_solution_plan_components_organization_id"), table_name="solution_plan_components"
    )
    op.drop_index("ix_solution_plan_components_evaluation", table_name="solution_plan_components")
    op.drop_table("solution_plan_components")
    op.drop_index(op.f("ix_score_components_organization_id"), table_name="score_components")
    op.drop_index("ix_score_components_evaluation", table_name="score_components")
    op.drop_table("score_components")
    op.drop_index(op.f("ix_score_bounds_organization_id"), table_name="score_bounds")
    op.drop_index("ix_score_bounds_evaluation_dimension", table_name="score_bounds")
    op.drop_table("score_bounds")
    op.drop_index(
        op.f("ix_robustness_frontiers_organization_id"), table_name="robustness_frontiers"
    )
    op.drop_index("ix_robustness_frontiers_evaluation", table_name="robustness_frontiers")
    op.drop_table("robustness_frontiers")
    op.drop_index(op.f("ix_identity_merges_organization_id"), table_name="identity_merges")
    op.drop_index("ix_identity_merges_canonical", table_name="identity_merges")
    op.drop_table("identity_merges")
    op.drop_index(
        op.f("ix_decision_gate_results_organization_id"), table_name="decision_gate_results"
    )
    op.drop_index("ix_decision_gate_results_evaluation", table_name="decision_gate_results")
    op.drop_table("decision_gate_results")
    op.drop_index(
        op.f("ix_candidate_set_members_organization_id"), table_name="candidate_set_members"
    )
    op.drop_index("ix_candidate_set_members_identity", table_name="candidate_set_members")
    op.drop_table("candidate_set_members")
    op.drop_index(op.f("ix_action_runs_organization_id"), table_name="action_runs")
    op.drop_index("ix_action_runs_decision_status", table_name="action_runs")
    op.drop_table("action_runs")
    op.drop_index(
        op.f("ix_evidence_assessments_organization_id"), table_name="evidence_assessments"
    )
    op.drop_index("ix_evidence_assessments_evaluation_field", table_name="evidence_assessments")
    op.drop_table("evidence_assessments")
    op.drop_index("ix_evaluation_solution_plans_rank", table_name="evaluation_solution_plans")
    op.drop_index(
        op.f("ix_evaluation_solution_plans_organization_id"), table_name="evaluation_solution_plans"
    )
    op.drop_table("evaluation_solution_plans")
    op.drop_index(op.f("ix_discovery_runs_organization_id"), table_name="discovery_runs")
    op.drop_table("discovery_runs")
    op.drop_index(
        op.f("ix_counterfactual_records_organization_id"), table_name="counterfactual_records"
    )
    op.drop_index("ix_counterfactual_records_decision", table_name="counterfactual_records")
    op.drop_index("ix_counterfactual_records_base_hash", table_name="counterfactual_records")
    op.drop_table("counterfactual_records")
    op.drop_index("ix_evaluation_runs_request_evaluated", table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_organization_id"), table_name="evaluation_runs")
    op.drop_index("ix_evaluation_runs_decision_id", table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index(
        op.f("ix_evaluation_pipeline_versions_organization_id"),
        table_name="evaluation_pipeline_versions",
    )
    op.drop_table("evaluation_pipeline_versions")
    # ### end Alembic commands ###
