"""initial vertical workflow

Revision ID: 403317721639
Revises:
Create Date: 2026-08-02 03:34:26.830288
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "403317721639"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = (
    "idempotency_records",
    "outbox_events",
    "purchase_requests",
    "stack_snapshots",
    "candidate_feedback",
    "engagements",
    "purchase_brief_versions",
    "stack_patches",
    "calibration_runs",
    "decision_records",
    "requirement_brief_versions",
    "purchase_intents",
    "approval_requests",
    "merchant_orders",
    "payment_sessions",
    "receipts",
    "approval_events",
    "entitlements",
    "payment_attempts",
    "transaction_transitions",
)


def _enable_tenant_rls() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    for table_name in TENANT_TABLES:
        op.execute(sa.text(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY'))
        op.execute(sa.text(f'ALTER TABLE "{table_name}" FORCE ROW LEVEL SECURITY'))
        op.execute(
            sa.text(
                f'CREATE POLICY tenant_isolation ON "{table_name}" '
                "USING (organization_id = current_setting('app.organization_id', true)) "
                "WITH CHECK (organization_id = current_setting('app.organization_id', true))"
            )
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("operation", sa.String(length=120), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column(
            "response_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("response_reference", sa.String(length=128), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "actor_id",
            "operation",
            "idempotency_key",
            name="uq_idempotency_scope",
        ),
    )
    op.create_index(
        op.f("ix_idempotency_records_organization_id"),
        "idempotency_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "event_key", name="uq_outbox_event_key"),
    )
    op.create_index(
        op.f("ix_outbox_events_organization_id"), "outbox_events", ["organization_id"], unique=False
    )
    op.create_table(
        "purchase_requests",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("intent", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("visibility", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("request_hash", sa.String(length=80), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "visibility IN ('PRIVATE','SELECTIVE','OPEN_RFP')",
            name="ck_purchase_request_visibility",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "request_hash", name="uq_purchase_request_hash"),
    )
    op.create_index(
        op.f("ix_purchase_requests_organization_id"),
        "purchase_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "stack_snapshots",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "lock",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("lock_hash", sa.String(length=80), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "lock_hash", name="uq_stack_lock_hash"),
        sa.UniqueConstraint("organization_id", "version", name="uq_stack_snapshot_version"),
    )
    op.create_index(
        op.f("ix_stack_snapshots_organization_id"),
        "stack_snapshots",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "candidate_feedback",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_request_id", sa.String(length=64), nullable=False),
        sa.Column("candidate_id", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column(
            "proposed_change",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('SHORTLIST','PASS','REQUEST_OFFER','SAVE_FOR_LATER','NOT_ENOUGH_EVIDENCE')",
            name="ck_candidate_feedback_action",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"], ["purchase_requests.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_feedback_organization_id"),
        "candidate_feedback",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "engagements",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_request_id", sa.String(length=64), nullable=False),
        sa.Column("candidate_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("buyer_consented", sa.Boolean(), nullable=False),
        sa.Column("seller_consented", sa.Boolean(), nullable=False),
        sa.Column(
            "contact_exchange",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('NOT_STARTED','SELLER_REVIEWING','SELLER_PASSED','OFFER_AVAILABLE','BUYER_CONSENT_PENDING','SELLER_CONSENT_PENDING','INTRODUCTION_READY','DECLINED','EXPIRED')",
            name="ck_engagement_status",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"], ["purchase_requests.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_engagements_organization_id"), "engagements", ["organization_id"], unique=False
    )
    op.create_table(
        "purchase_brief_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_request_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=80), nullable=False),
        sa.Column("supersedes_id", sa.String(length=64), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"], ["purchase_requests.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"], ["purchase_brief_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "purchase_request_id", "version", name="uq_purchase_brief_version"
        ),
    )
    op.create_index(
        op.f("ix_purchase_brief_versions_organization_id"),
        "purchase_brief_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "stack_patches",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("base_snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("base_version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("patch_hash", sa.String(length=80), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["base_snapshot_id"], ["stack_snapshots.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stack_patches_organization_id"), "stack_patches", ["organization_id"], unique=False
    )
    op.create_table(
        "calibration_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_request_id", sa.String(length=64), nullable=False),
        sa.Column("purchase_brief_id", sa.String(length=64), nullable=False),
        sa.Column(
            "result",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("proposed_purchase_brief_id", sa.String(length=64), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["proposed_purchase_brief_id"], ["purchase_brief_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["purchase_brief_id"], ["purchase_brief_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"], ["purchase_requests.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_calibration_runs_organization_id"),
        "calibration_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "decision_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_request_id", sa.String(length=64), nullable=False),
        sa.Column("purchase_brief_id", sa.String(length=64), nullable=False),
        sa.Column("decision_hash", sa.String(length=80), nullable=False),
        sa.Column("selected_solution_plan_id", sa.String(length=64), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_brief_id"], ["purchase_brief_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"], ["purchase_requests.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "decision_hash", name="uq_decision_hash"),
    )
    op.create_index(
        op.f("ix_decision_records_organization_id"),
        "decision_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "requirement_brief_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_request_id", sa.String(length=64), nullable=False),
        sa.Column("purchase_brief_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=80), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_brief_id"], ["purchase_brief_versions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["purchase_request_id"], ["purchase_requests.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "purchase_request_id", "version", name="uq_requirement_brief_version"
        ),
    )
    op.create_index(
        op.f("ix_requirement_brief_versions_organization_id"),
        "requirement_brief_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "purchase_intents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("decision_hash", sa.String(length=80), nullable=False),
        sa.Column("solution_plan_id", sa.String(length=64), nullable=False),
        sa.Column("intent_hash", sa.String(length=80), nullable=False),
        sa.Column("merchant_id", sa.String(length=100), nullable=False),
        sa.Column("merchant_name", sa.String(length=200), nullable=False),
        sa.Column("merchant_url", sa.Text(), nullable=False),
        sa.Column("approved_merchant_chain_id", sa.String(length=64), nullable=False),
        sa.Column("pack_id", sa.String(length=100), nullable=False),
        sa.Column("pack_version", sa.Integer(), nullable=False),
        sa.Column("offer_id", sa.String(length=100), nullable=False),
        sa.Column("offer_version", sa.Integer(), nullable=False),
        sa.Column("quote_id", sa.String(length=100), nullable=False),
        sa.Column("quote_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "expected_fulfillments",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("approval_status", sa.String(length=32), nullable=False),
        sa.Column("payment_status", sa.String(length=32), nullable=False),
        sa.Column("fulfillment_status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "approval_status IN ('NOT_REQUESTED','PENDING','APPROVED','REJECTED','EXPIRED','SUPERSEDED')",
            name="ck_purchase_intent_approval_status",
        ),
        sa.CheckConstraint(
            "fulfillment_status IN ('NOT_STARTED','PENDING','PARTIAL','VERIFIED','FAILED_RETRYABLE','FAILED_FINAL','REVOKED')",
            name="ck_purchase_intent_fulfillment_status",
        ),
        sa.CheckConstraint(
            "payment_status IN ('NOT_STARTED','SESSION_CREATED','CARDHOLDER_PENDING','CHECKOUT_PENDING','MERCHANT_APPROVED','REPORTING','PRAVA_COMPLETED','DECLINED','EXPIRED','UNCERTAIN','FAILED')",
            name="ck_purchase_intent_payment_status",
        ),
        sa.CheckConstraint("amount >= 0", name="ck_purchase_intent_amount_nonnegative"),
        sa.CheckConstraint("currency = upper(currency)", name="ck_purchase_intent_currency_upper"),
        sa.ForeignKeyConstraint(["decision_id"], ["decision_records.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "intent_hash", name="uq_purchase_intent_hash"),
    )
    op.create_index(
        op.f("ix_purchase_intents_organization_id"),
        "purchase_intents",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_intent_id", sa.String(length=64), nullable=False),
        sa.Column("intent_hash", sa.String(length=80), nullable=False),
        sa.Column("policy_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "required_roles",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "approved_roles",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_intent_id"], ["purchase_intents.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "purchase_intent_id", "intent_hash", name="uq_approval_exact_intent"
        ),
    )
    op.create_index(
        op.f("ix_approval_requests_organization_id"),
        "approval_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "merchant_orders",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_intent_id", sa.String(length=64), nullable=False),
        sa.Column("merchant_adapter_id", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("external_order_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "safe_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_intent_id"], ["purchase_intents.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "merchant_adapter_id", "external_order_id", name="uq_merchant_external_order"
        ),
        sa.UniqueConstraint(
            "merchant_adapter_id", "idempotency_key", name="uq_merchant_order_provider_key"
        ),
    )
    op.create_index(
        op.f("ix_merchant_orders_organization_id"),
        "merchant_orders",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "payment_sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_intent_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_session_id", sa.String(length=128), nullable=False),
        sa.Column("provider_order_id", sa.String(length=128), nullable=False),
        sa.Column("hosted_url", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_intent_id"], ["purchase_intents.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_session_id", name="uq_provider_payment_session"),
    )
    op.create_index(
        op.f("ix_payment_sessions_organization_id"),
        "payment_sessions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "receipts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_intent_id", sa.String(length=64), nullable=False),
        sa.Column("receipt_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_intent_id"], ["purchase_intents.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("purchase_intent_id"),
    )
    op.create_index(
        op.f("ix_receipts_organization_id"), "receipts", ["organization_id"], unique=False
    )
    op.create_table(
        "approval_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("approval_request_id", sa.String(length=64), nullable=False),
        sa.Column("intent_hash", sa.String(length=80), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("actor_role", sa.String(length=80), nullable=False),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "action IN ('APPROVE','REJECT','DELEGATE')", name="ck_approval_event_action"
        ),
        sa.ForeignKeyConstraint(
            ["approval_request_id"], ["approval_requests.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "event_key", name="uq_approval_event_key"),
    )
    op.create_index(
        op.f("ix_approval_events_organization_id"),
        "approval_events",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "entitlements",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_intent_id", sa.String(length=64), nullable=False),
        sa.Column("merchant_order_id", sa.String(length=64), nullable=False),
        sa.Column("fulfillment_adapter_id", sa.String(length=80), nullable=False),
        sa.Column("external_entitlement_id", sa.String(length=128), nullable=False),
        sa.Column("fulfillment_item_id", sa.String(length=100), nullable=False),
        sa.Column("entitlement_type", sa.String(length=80), nullable=False),
        sa.Column("subject_type", sa.String(length=80), nullable=False),
        sa.Column("subject_id", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column(
            "safe_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name="ck_entitlement_quantity_nonnegative"),
        sa.ForeignKeyConstraint(["merchant_order_id"], ["merchant_orders.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_intent_id"], ["purchase_intents.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "fulfillment_adapter_id", "external_entitlement_id", name="uq_external_entitlement"
        ),
    )
    op.create_index(
        op.f("ix_entitlements_organization_id"), "entitlements", ["organization_id"], unique=False
    )
    op.create_table(
        "payment_attempts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_intent_id", sa.String(length=64), nullable=False),
        sa.Column("payment_session_id", sa.String(length=64), nullable=False),
        sa.Column("merchant_outcome", sa.String(length=24), nullable=True),
        sa.Column("external_order_id", sa.String(length=128), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["payment_session_id"], ["payment_sessions.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["purchase_intent_id"], ["purchase_intents.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_attempts_organization_id"),
        "payment_attempts",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "uq_charged_or_uncertain_intent",
        "payment_attempts",
        ["purchase_intent_id"],
        unique=True,
        postgresql_where=sa.text("merchant_outcome IN ('approved','unknown')"),
    )
    op.create_index(
        "uq_open_payment_attempt",
        "payment_attempts",
        ["purchase_intent_id"],
        unique=True,
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.create_table(
        "transaction_transitions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("purchase_intent_id", sa.String(length=64), nullable=False),
        sa.Column("from_state", sa.String(length=32), nullable=True),
        sa.Column("to_state", sa.String(length=32), nullable=False),
        sa.Column("attempt_id", sa.String(length=64), nullable=True),
        sa.Column("actor_type", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("reason_code", sa.String(length=80), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("provider_event_ref", sa.String(length=128), nullable=True),
        sa.Column("payload_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["payment_attempts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["purchase_intent_id"], ["purchase_intents.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "purchase_intent_id", "event_key", name="uq_transaction_event_key"
        ),
    )
    op.create_index(
        op.f("ix_transaction_transitions_organization_id"),
        "transaction_transitions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "uq_provider_event_ref",
        "transaction_transitions",
        ["organization_id", "provider_event_ref"],
        unique=True,
        postgresql_where=sa.text("provider_event_ref IS NOT NULL"),
    )
    _enable_tenant_rls()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_provider_event_ref",
        table_name="transaction_transitions",
        postgresql_where=sa.text("provider_event_ref IS NOT NULL"),
    )
    op.drop_index(
        op.f("ix_transaction_transitions_organization_id"), table_name="transaction_transitions"
    )
    op.drop_table("transaction_transitions")
    op.drop_index(
        "uq_open_payment_attempt",
        table_name="payment_attempts",
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    op.drop_index(
        "uq_charged_or_uncertain_intent",
        table_name="payment_attempts",
        postgresql_where=sa.text("merchant_outcome IN ('approved','unknown')"),
    )
    op.drop_index(op.f("ix_payment_attempts_organization_id"), table_name="payment_attempts")
    op.drop_table("payment_attempts")
    op.drop_index(op.f("ix_entitlements_organization_id"), table_name="entitlements")
    op.drop_table("entitlements")
    op.drop_index(op.f("ix_approval_events_organization_id"), table_name="approval_events")
    op.drop_table("approval_events")
    op.drop_index(op.f("ix_receipts_organization_id"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_index(op.f("ix_payment_sessions_organization_id"), table_name="payment_sessions")
    op.drop_table("payment_sessions")
    op.drop_index(op.f("ix_merchant_orders_organization_id"), table_name="merchant_orders")
    op.drop_table("merchant_orders")
    op.drop_index(op.f("ix_approval_requests_organization_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index(op.f("ix_purchase_intents_organization_id"), table_name="purchase_intents")
    op.drop_table("purchase_intents")
    op.drop_index(
        op.f("ix_requirement_brief_versions_organization_id"),
        table_name="requirement_brief_versions",
    )
    op.drop_table("requirement_brief_versions")
    op.drop_index(op.f("ix_decision_records_organization_id"), table_name="decision_records")
    op.drop_table("decision_records")
    op.drop_index(op.f("ix_calibration_runs_organization_id"), table_name="calibration_runs")
    op.drop_table("calibration_runs")
    op.drop_index(op.f("ix_stack_patches_organization_id"), table_name="stack_patches")
    op.drop_table("stack_patches")
    op.drop_index(
        op.f("ix_purchase_brief_versions_organization_id"), table_name="purchase_brief_versions"
    )
    op.drop_table("purchase_brief_versions")
    op.drop_index(op.f("ix_engagements_organization_id"), table_name="engagements")
    op.drop_table("engagements")
    op.drop_index(op.f("ix_candidate_feedback_organization_id"), table_name="candidate_feedback")
    op.drop_table("candidate_feedback")
    op.drop_index(op.f("ix_stack_snapshots_organization_id"), table_name="stack_snapshots")
    op.drop_table("stack_snapshots")
    op.drop_index(op.f("ix_purchase_requests_organization_id"), table_name="purchase_requests")
    op.drop_table("purchase_requests")
    op.drop_index(op.f("ix_outbox_events_organization_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_idempotency_records_organization_id"), table_name="idempotency_records")
    op.drop_table("idempotency_records")
    op.drop_table("organizations")
    # ### end Alembic commands ###
