"""add workflow runs

Revision ID: 744f4ab939df
Revises: 403317721639
Create Date: 2026-08-02 03:50:35.920810
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "744f4ab939df"
down_revision: str | None = "403317721639"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("result_reference", sa.String(length=160), nullable=True),
        sa.Column("safe_error_code", sa.String(length=80), nullable=True),
        sa.Column(
            "event_log",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','RUNNING','COMPLETED','FAILED')", name="ck_workflow_status"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "aggregate_type",
            "aggregate_id",
            "operation",
            name="uq_workflow_identity",
        ),
    )
    op.create_index(
        op.f("ix_workflow_runs_organization_id"), "workflow_runs", ["organization_id"], unique=False
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text('ALTER TABLE "workflow_runs" ENABLE ROW LEVEL SECURITY'))
        op.execute(sa.text('ALTER TABLE "workflow_runs" FORCE ROW LEVEL SECURITY'))
        op.execute(
            sa.text(
                'CREATE POLICY tenant_isolation ON "workflow_runs" '
                "USING (organization_id = current_setting('app.organization_id', true)) "
                "WITH CHECK (organization_id = current_setting('app.organization_id', true))"
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_runs_organization_id"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    # ### end Alembic commands ###
