"""add seller evidence workflow

Revision ID: ec4ca586ccc9
Revises: a6f4c2d9e801
Create Date: 2026-08-02 05:58:34.534880
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "ec4ca586ccc9"
down_revision: str | None = "a6f4c2d9e801"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TENANT_TABLES = (
    "seller_products",
    "seller_activity_events",
    "seller_pack_drafts",
    "seller_product_claims",
    "seller_evidence_attachments",
    "seller_pack_draft_revisions",
    "seller_pack_versions",
    "seller_review_submissions",
    "seller_pack_export_artifacts",
    "seller_pack_suspensions",
    "seller_review_decisions",
)


def _enable_tenant_rls() -> None:
    connection = op.get_bind()
    if connection.dialect.name != "postgresql":
        return
    expression = "organization_id = NULLIF(current_setting('app.organization_id', true), '')"
    for table_name in TENANT_TABLES:
        op.execute(sa.text(f'ALTER TABLE "{table_name}" ENABLE ROW LEVEL SECURITY'))
        op.execute(sa.text(f'ALTER TABLE "{table_name}" FORCE ROW LEVEL SECURITY'))
        op.execute(
            sa.text(
                f'CREATE POLICY tenant_access ON "{table_name}" AS PERMISSIVE FOR ALL TO PUBLIC '
                f"USING ({expression}) WITH CHECK ({expression})"
            )
        )
        op.execute(
            sa.text(
                f'CREATE POLICY tenant_isolation ON "{table_name}" '
                f"AS RESTRICTIVE FOR ALL TO PUBLIC USING ({expression}) WITH CHECK ({expression})"
            )
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seller_products",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("public_summary", sa.Text(), nullable=False),
        sa.Column("publisher_authority", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("owner_actor_id", sa.String(length=100), nullable=True),
        sa.Column("current_draft_id", sa.String(length=64), nullable=True),
        sa.Column("current_pack_version_id", sa.String(length=64), nullable=True),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("fixture_label", sa.String(length=80), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "publisher_authority IN ('SELLER_SEALED','PLATFORM_COMPILED','EXTERNAL_UNSEALED')",
            name="ck_seller_product_authority",
        ),
        sa.CheckConstraint(
            "state IN ('UNCLAIMED','CLAIM_PENDING','CLAIM_DENIED','SELLER_DRAFT','VALIDATION_CONFLICT','IN_REVIEW','CHANGES_REQUESTED','PUBLISH_READY','PUBLISHED','SUPERSEDED','PUBLICATION_FAILED')",
            name="ck_seller_product_state",
        ),
        sa.CheckConstraint("current_version >= 1", name="ck_seller_product_version"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "name", "category", name="uq_seller_product_identity"
        ),
    )
    op.create_index(
        op.f("ix_seller_products_organization_id"),
        "seller_products",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "seller_activity_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("session_id", sa.String(length=100), nullable=False),
        sa.Column("question_fingerprint", sa.String(length=80), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fixture_label", sa.String(length=80), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('ANSWER_RENDERED','SELLER_HANDOFF_REQUESTED')",
            name="ck_seller_activity_type",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["seller_products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_seller_activity_events_organization_id"),
        "seller_activity_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_seller_activity_window",
        "seller_activity_events",
        ["organization_id", "product_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "seller_pack_drafts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("editor_actor_id", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("publisher_authority", sa.String(length=32), nullable=False),
        sa.Column("current_revision", sa.Integer(), nullable=False),
        sa.Column("current_revision_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "validation",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("based_on_pack_version_id", sa.String(length=64), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "publisher_authority IN ('SELLER_SEALED','PLATFORM_COMPILED','EXTERNAL_UNSEALED')",
            name="ck_seller_draft_authority",
        ),
        sa.CheckConstraint(
            "state IN ('SELLER_DRAFT','VALIDATION_CONFLICT','IN_REVIEW','CHANGES_REQUESTED','PUBLISH_READY','PUBLISHED','SUPERSEDED','PUBLICATION_FAILED')",
            name="ck_seller_draft_state",
        ),
        sa.CheckConstraint("current_revision >= 1", name="ck_seller_draft_revision"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["seller_products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "product_id", name="uq_seller_current_draft"),
    )
    op.create_index(
        op.f("ix_seller_pack_drafts_organization_id"),
        "seller_pack_drafts",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "seller_product_claims",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("claimant_actor_id", sa.String(length=100), nullable=False),
        sa.Column("requested_role", sa.String(length=32), nullable=False),
        sa.Column("authority_proof_hash", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("safe_reason", sa.String(length=500), nullable=True),
        sa.Column("decided_by_actor_id", sa.String(length=100), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "requested_role IN ('SELLER_EDITOR','SELLER_REVIEWER')", name="ck_seller_claim_role"
        ),
        sa.CheckConstraint(
            "state IN ('CLAIM_PENDING','CLAIM_DENIED','SELLER_DRAFT')", name="ck_seller_claim_state"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["seller_products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "product_id",
            "claimant_actor_id",
            "authority_proof_hash",
            name="uq_seller_claim_proof",
        ),
    )
    op.create_index(
        "ix_seller_claim_product_state",
        "seller_product_claims",
        ["organization_id", "product_id", "state"],
        unique=False,
    )
    op.create_index(
        op.f("ix_seller_product_claims_organization_id"),
        "seller_product_claims",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "seller_evidence_attachments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("draft_id", sa.String(length=64), nullable=False),
        sa.Column("attached_revision", sa.Integer(), nullable=False),
        sa.Column("source_reference_hash", sa.String(length=80), nullable=False),
        sa.Column("public_source_url", sa.String(length=500), nullable=True),
        sa.Column("source_class", sa.String(length=80), nullable=False),
        sa.Column(
            "claim_fields",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_state", sa.String(length=24), nullable=False),
        sa.Column("verification_actor_id", sa.String(length=100), nullable=True),
        sa.Column("verification_method", sa.String(length=100), nullable=True),
        sa.Column("added_by_actor_id", sa.String(length=100), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "verification_state IN ('UNVERIFIED','PENDING','VERIFIED','REJECTED')",
            name="ck_seller_evidence_verification",
        ),
        sa.CheckConstraint("attached_revision >= 1", name="ck_seller_evidence_revision"),
        sa.ForeignKeyConstraint(["draft_id"], ["seller_pack_drafts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "draft_id", "source_reference_hash", name="uq_seller_evidence_source"
        ),
    )
    op.create_index(
        op.f("ix_seller_evidence_attachments_organization_id"),
        "seller_evidence_attachments",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "seller_pack_draft_revisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("draft_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("revision_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "claims",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "fit_rules",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "anti_fit_rules",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "validation",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("created_by_actor_id", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint("revision >= 1", name="ck_seller_draft_snapshot_revision"),
        sa.ForeignKeyConstraint(["draft_id"], ["seller_pack_drafts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "draft_id", "revision", name="uq_seller_draft_revision"
        ),
        sa.UniqueConstraint(
            "organization_id", "draft_id", "revision_hash", name="uq_seller_draft_hash"
        ),
    )
    op.create_index(
        op.f("ix_seller_pack_draft_revisions_organization_id"),
        "seller_pack_draft_revisions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "seller_pack_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("product_id", sa.String(length=64), nullable=False),
        sa.Column("source_draft_id", sa.String(length=64), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("source_revision_hash", sa.String(length=80), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=80), nullable=False),
        sa.Column("publisher_authority", sa.String(length=32), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("published_by_actor_id", sa.String(length=100), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_by_version_id", sa.String(length=64), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "publisher_authority IN ('SELLER_SEALED','PLATFORM_COMPILED')",
            name="ck_seller_pack_published_authority",
        ),
        sa.CheckConstraint("source_revision >= 1", name="ck_seller_pack_source_revision"),
        sa.CheckConstraint("version >= 1", name="ck_seller_pack_version"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["seller_products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["source_draft_id"], ["seller_pack_drafts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "content_hash", name="uq_seller_pack_content_hash"),
        sa.UniqueConstraint(
            "organization_id", "product_id", "version", name="uq_seller_pack_version"
        ),
    )
    op.create_index(
        op.f("ix_seller_pack_versions_organization_id"),
        "seller_pack_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "seller_review_submissions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("draft_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("revision_hash", sa.String(length=80), nullable=False),
        sa.Column("submitted_by_actor_id", sa.String(length=100), nullable=False),
        sa.Column("reviewer_role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "reviewer_role IN ('SELLER_REVIEWER','PLATFORM_OPERATOR')", name="ck_seller_review_role"
        ),
        sa.CheckConstraint("status IN ('PENDING','COMPLETED')", name="ck_seller_review_status"),
        sa.CheckConstraint("revision >= 1", name="ck_seller_review_revision"),
        sa.ForeignKeyConstraint(["draft_id"], ["seller_pack_drafts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "draft_id", "revision_hash", name="uq_seller_review_submission"
        ),
    )
    op.create_index(
        op.f("ix_seller_review_submissions_organization_id"),
        "seller_review_submissions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "seller_pack_export_artifacts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("pack_version_id", sa.String(length=64), nullable=False),
        sa.Column("format", sa.String(length=24), nullable=False),
        sa.Column("content_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(none_as_null=True, astext_type=Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "format IN ('JSON','HTML','REUSABLE_ANSWER')", name="ck_seller_export_format"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["pack_version_id"], ["seller_pack_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "pack_version_id", "format", name="uq_seller_pack_export"
        ),
    )
    op.create_index(
        op.f("ix_seller_pack_export_artifacts_organization_id"),
        "seller_pack_export_artifacts",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "seller_pack_suspensions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("pack_version_id", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["pack_version_id"], ["seller_pack_versions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "event_key", name="uq_seller_suspension_event"),
    )
    op.create_index(
        op.f("ix_seller_pack_suspensions_organization_id"),
        "seller_pack_suspensions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "seller_review_decisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("submission_id", sa.String(length=64), nullable=False),
        sa.Column("draft_id", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("revision_hash", sa.String(length=80), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("event_key", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "actor_role IN ('SELLER_REVIEWER','PLATFORM_OPERATOR')",
            name="ck_seller_review_actor_role",
        ),
        sa.CheckConstraint(
            "decision IN ('REQUEST_CHANGES','APPROVE','REJECT')", name="ck_seller_review_decision"
        ),
        sa.ForeignKeyConstraint(["draft_id"], ["seller_pack_drafts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["seller_review_submissions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "event_key", name="uq_seller_review_event"),
        sa.UniqueConstraint(
            "organization_id", "submission_id", name="uq_seller_review_final_decision"
        ),
    )
    op.create_index(
        op.f("ix_seller_review_decisions_organization_id"),
        "seller_review_decisions",
        ["organization_id"],
        unique=False,
    )
    _enable_tenant_rls()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_seller_review_decisions_organization_id"), table_name="seller_review_decisions"
    )
    op.drop_table("seller_review_decisions")
    op.drop_index(
        op.f("ix_seller_pack_suspensions_organization_id"), table_name="seller_pack_suspensions"
    )
    op.drop_table("seller_pack_suspensions")
    op.drop_index(
        op.f("ix_seller_pack_export_artifacts_organization_id"),
        table_name="seller_pack_export_artifacts",
    )
    op.drop_table("seller_pack_export_artifacts")
    op.drop_index(
        op.f("ix_seller_review_submissions_organization_id"), table_name="seller_review_submissions"
    )
    op.drop_table("seller_review_submissions")
    op.drop_index(
        op.f("ix_seller_pack_versions_organization_id"), table_name="seller_pack_versions"
    )
    op.drop_table("seller_pack_versions")
    op.drop_index(
        op.f("ix_seller_pack_draft_revisions_organization_id"),
        table_name="seller_pack_draft_revisions",
    )
    op.drop_table("seller_pack_draft_revisions")
    op.drop_index(
        op.f("ix_seller_evidence_attachments_organization_id"),
        table_name="seller_evidence_attachments",
    )
    op.drop_table("seller_evidence_attachments")
    op.drop_index(
        op.f("ix_seller_product_claims_organization_id"), table_name="seller_product_claims"
    )
    op.drop_index("ix_seller_claim_product_state", table_name="seller_product_claims")
    op.drop_table("seller_product_claims")
    op.drop_index(op.f("ix_seller_pack_drafts_organization_id"), table_name="seller_pack_drafts")
    op.drop_table("seller_pack_drafts")
    op.drop_index("ix_seller_activity_window", table_name="seller_activity_events")
    op.drop_index(
        op.f("ix_seller_activity_events_organization_id"), table_name="seller_activity_events"
    )
    op.drop_table("seller_activity_events")
    op.drop_index(op.f("ix_seller_products_organization_id"), table_name="seller_products")
    op.drop_table("seller_products")
    # ### end Alembic commands ###
